config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from opencourse.profiles.views import ProfileView

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/profile/", ProfileView.as_view()),
    path("profiles/", include("opencourse.profiles.urls", namespace="profiles")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("courses/", include("opencourse.courses.urls", namespace="courses")),
    path("", RedirectView.as_view(pattern_name="courses:search")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path("rosetta/", include("rosetta.urls"))]

opencourse/courses/urls.py
from django.urls import path, include
from django.views.generic import RedirectView

from . import views

app_name = "courses"

course_patterns = [
    path("list/", views.CourseListView.as_view(), name="list"),
    path("create/", views.CourseCreateView.as_view(), name="create"),
    path("detail/<int:pk>/", views.CourseDetailView.as_view(), name="detail"),
    path("edit/<int:pk>/", views.CourseEditView.as_view(), name="edit"),
    path("delete/<int:pk>/", views.CourseDeleteView.as_view(), name="delete"),
    path("search/", views.CourseSearchView.as_view(), name="search"),
    path(
        "<int:pk>/students/",
        views.CourseStudentsListView.as_view(),
        name="students_list",
    ),
    path(
        "search-results/",
        views.CourseSearchResultsView.as_view(),
        name="search_results",
    ),
]

enrollment_patterns = [
    path(
        "professor/", views.EnrollmentProfessorListView.as_view(), name="professor_list"
    ),
    path("student/", views.EnrollmentStudentListView.as_view(), name="student_list"),
    path("create", views.EnrollmentCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.EnrollmentUpdateStatusView.as_view(), name="edit"),
]

handout_patterns = [
    path("list/<int:course_pk>/", views.HandoutListView.as_view(), name="list"),
    path("create/<int:course_pk>/", views.HandoutCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.HandoutUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", views.HandoutDeleteView.as_view(), name="delete"),
]

center_patterns = [
    path("list/", views.CenterListView.as_view(), name="list"),
    path("create/", views.CenterCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.CenterEditView.as_view(), name="edit"),
    path("delete/<int:pk>/", views.CenterDeleteView.as_view(), name="delete"),
    path("detail/<int:pk>/", views.CenterDetailView.as_view(), name="detail"),
    path(
        "search-results/",
        views.CenterSearchResultsView.as_view(),
        name="search_results",
    ),
]

join_request_patterns = [
    path("admin/", views.JoinRequestrListView.as_view(), name="admin_list"),
    path("create/", views.JoinRequestCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.JoinRequestUpdateView.as_view(), name="edit"),
]

urlpatterns = [
    path("", include(course_patterns)),
    path(
        "enrollments/",
        include((enrollment_patterns, "opencourse.courses"), namespace="enrollments"),
    ),
    path(
        "handouts/",
        include((handout_patterns, "opencourse.courses"), namespace="handouts"),
    ),
    path(
        "centers/",
        include((center_patterns, "opencourse.courses"), namespace="centers"),
    ),
    path(
        "join_requests/",
        include(
            (join_request_patterns, "opencourse.courses"), namespace="join_requests"
        ),
    ),
]

opencourse/profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"
urlpatterns = [
    path("", views.ProfileView.as_view(), name="profile"),
    path("dispatch-login/", views.DispatchLoginView.as_view(), name="dispatch_login",),
    path("professor/", views.ProfessorUpdateView.as_view(), name="professor"),
    path(
        "professor/<int:pk>/add-review",
        views.ReviewCreateView.as_view(),
        name="review_create",
    ),
    path(
        "professor/<int:pk>/contact-request/",
        views.ContactRequestView.as_view(),
        name="contact_request",
    ),
    path("student/", views.StudentUpdateView.as_view(), name="student"),
    path("403/", views.ForbiddenView.as_view(), name="403"),
]

opencourse/courses/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from . import managers
from opencourse.profiles.models import Professor, Student


class City(models.Model):
    codepostal = models.CharField(max_length=8, blank=True, null=True)
    name = models.CharField(max_length=60, blank=True, null=True)
    latitude_south = models.DecimalField(
        blank=True, null=True, max_digits=8, decimal_places=4
    )
    latitude_north = models.DecimalField(
        blank=True, null=True, max_digits=8, decimal_places=4
    )
    longitude_west = models.DecimalField(
        blank=True, null=True, max_digits=8, decimal_places=4
    )
    longitude_east = models.DecimalField(
        blank=True, null=True, max_digits=8, decimal_places=4
    )
    latitude_southa = models.DecimalField(
        blank=True, null=True, max_digits=8, decimal_places=4
    )
    latitude_northa = models.DecimalField(
        blank=True, null=True, max_digits=8, decimal_places=4
    )
    longitude_westa = models.DecimalField(
        blank=True, null=True, max_digits=8, decimal_places=4
    )
    longitude_easta = models.DecimalField(
        blank=True, null=True, max_digits=8, decimal_places=4
    )
    category_1 = models.SmallIntegerField(blank=True, null=True)
    category_2 = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        verbose_name = _("City")
        verbose_name_plural = _("Cities")

    def __str__(self):
        return str(self.name)


class CourseLevel(models.Model):
    name = models.CharField(max_length=30, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = _("Level")
        verbose_name_plural = _("Levels")

    def __str__(self):
        return str(self.name)


class CourseDuration(models.Model):
    duration = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        verbose_name = _("Duration")
        verbose_name_plural = _("Durations")

    def __str__(self):
        return f"{self.duration} {_('minutes')}"


class CourseAge(models.Model):
    max = models.SmallIntegerField(blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = _("Age")
        verbose_name_plural = _("Ages")

    def __str__(self):
        return str(self.name)


class CourseArea(models.Model):
    name = models.CharField(max_length=30, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = _("Area")
        verbose_name_plural = _("Areas")

    def __str__(self):
        return str(self.name)


class CourseLanguage(models.Model):
    name = models.CharField(max_length=30, blank=True, null=True)
    tag = models.CharField(max_length=2, blank=True, null=True)

    class Meta:
        verbose_name = _("Language")
        verbose_name_plural = _("Languages")

    def __str__(self):
        return str(self.name)


class Center(models.Model):
    admin = models.ForeignKey(Professor, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    description = models.TextField(max_length=255, blank=True, null=True)
    picture = models.ImageField(
        upload_to="center_pics/%Y-%m-%d/", null=True, blank=True
    )
    created = models.DateTimeField(auto_now=True, blank=True, null=True)

    objects = managers.CenterManager()

    class Meta:
        verbose_name = _("Center")
        verbose_name_plural = _("Centers")
        permissions = (("manage_center", _("Manage center")),)

    def __str__(self):
        return str(self.name)


class Course(models.Model):
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    descrip = models.TextField(blank=True)
    extrainfo = models.CharField(max_length=250, blank=True, null=True)
    payactive = models.NullBooleanField()
    active = models.NullBooleanField()
    dateexp = models.DateTimeField(blank=True, null=True)
    starthostdate = models.DateTimeField(blank=True, null=True)
    endhostdate = models.DateTimeField(blank=True, null=True)
    hosted = models.NullBooleanField()
    hostactive = models.NullBooleanField()
    level = models.ForeignKey(CourseLevel, on_delete=models.SET_NULL, null=True)
    duration = models.ForeignKey(CourseDuration, on_delete=models.PROTECT, null=True)
    age = models.ManyToManyField(CourseAge)
    area = models.ManyToManyField(CourseArea)
    language = models.ManyToManyField(CourseLanguage)
    center = models.ForeignKey(Center, on_delete=models.SET_NULL, null=True)

    objects = managers.CourseManager()

    class Meta:
        verbose_name = _("Course")
        verbose_name_plural = _("Courses")
        permissions = (("manage_course", _("Manage course")),)

    def __str__(self):
        return self.title or ""


class CourseLocationType(models.Model):
    name = models.CharField(max_length=25)

    class Meta:
        verbose_name = _("Location Type")
        verbose_name_plural = _("Location Types")

    def __str__(self):
        return str(self.name)


class Currency(models.Model):
    name = models.CharField(max_length=20)
    iso_code = models.CharField(max_length=5)
    symbol = models.CharField(max_length=5)

    class Meta:
        verbose_name = _("Currency")
        verbose_name_plural = _("Currencies")

    def __str__(self):
        return self.symbol


class CourseLocation(models.Model):
    location_type = models.ForeignKey(
        CourseLocationType, on_delete=models.PROTECT, null=True
    )
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="locations"
    )
    description = models.CharField(max_length=100, blank=True, null=True)
    price = models.SmallIntegerField()
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)
    number_sessions = models.SmallIntegerField(blank=True, null=True)
    coursestartdate = models.DateTimeField(blank=True, null=True)
    courseenddate = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = _("Location")
        verbose_name_plural = _("Locations")

    def __str__(self):
        return f"{self.location_type.name}: {self.price}{self.currency}"


class Enrollment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    accepted = models.NullBooleanField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    objects = managers.EnrollmentManager()

    class Meta:
        verbose_name = _("Enrollment")
        verbose_name_plural = _("Enrollment")
        permissions = (("manage_enrollment", _("Manage enrollment")),)
        unique_together = ("course", "student")

    def __str__(self):
        return "{}: {} ({})".format(self.course, self.student, self.accepted)


class HandoutSection(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return str(self.name)


class Handout(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    description = models.TextField(max_length=255, blank=True, null=True)
    attachment = models.FileField(upload_to="handouts/%Y-%m-%d/")
    section = models.ForeignKey(HandoutSection, on_delete=models.PROTECT)

    objects = managers.HandoutManager()

    class Meta:
        verbose_name = _("Handout")
        verbose_name_plural = _("Handout")
        permissions = (("manage_handout", _("Manage handout")),)

    def __str__(self):
        return str(self.name)


class JoinRequest(models.Model):
    center = models.ForeignKey(Center, on_delete=models.CASCADE)
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    accepted = models.NullBooleanField()

    objects = managers.JoinRequestManager()

    class Meta:
        verbose_name = _("Join request")
        verbose_name_plural = _("Join requests")
        permissions = (("manage_join_request", _("Manage join request")),)
        unique_together = ("center", "professor")

    def __str__(self):
        return "{}: {} ({})".format(self.center, self.professor, self.accepted)

opencourse/profiles/views.py
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import (
    UpdateView,
    RedirectView,
    CreateView,
    View,
    TemplateView,
)
from django.contrib.auth import get_user_model
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from . import forms, models
from .mixins import (
    ProfessorRequiredMixin,
    StudentRequiredMixin,
)
from opencourse.courses.models import Course

User = get_user_model()


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ["first_name", "last_name"]
    formset_class = None

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["formset"] = self.formset_class(
                self.request.POST, self.request.FILES, instance=self.object
            )
        else:
            context["formset"] = self.formset_class(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        formset = context["formset"]
        if formset.is_valid():
            response = super().form_valid(form)
            formset.instance = self.object
            formset.save()
            return response
        else:
            return super().form_invalid(form)


class ProfessorUpdateView(ProfessorRequiredMixin, ProfileUpdateView):
    template_name = "profiles/profile.html"
    success_url = reverse_lazy("courses:list")
    formset_class = forms.ProfessorFormSet


class StudentUpdateView(StudentRequiredMixin, ProfileUpdateView):
    template_name = "profiles/profile.html"
    success_url = reverse_lazy("courses:search")
    formset_class = forms.StudentFormSet


class ProfileView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        if hasattr(self.request.user, "professor"):
            return reverse_lazy("profiles:professor")
        elif hasattr(self.request.user, "student"):
            return reverse_lazy("profiles:student")
        return super().get_redirect_url(*args, **kwargs)


class DispatchLoginView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        if hasattr(self.request.user, "professor"):
            if self.request.user.professor.course_set.exists():
                return reverse_lazy("courses:list")
            else:
                return reverse_lazy("courses:create")
        return reverse_lazy("courses:search")


class ReviewCreateView(LoginRequiredMixin, StudentRequiredMixin, CreateView):
    form_class = forms.ReviewForm

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse_lazy("courses:detail", args=[pk])

    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        pk = self.kwargs["pk"]
        course = Course.objects.filter(pk=pk).first()
        form.instance.professor = course.professor
        return super().form_valid(form)


class ContactRequestView(SingleObjectMixin, View):
    model = models.Professor

    def post(self, *args, **kwargs):
        professor = self.get_object()
        professor.contacts_requests += 1
        professor.save()
        return HttpResponse()


class ForbiddenView(TemplateView):
    template_name = "profiles/../templates/403.html"

opencourse/templates/courses/center_edit.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content_title %}
  <h2 class="h3">{% trans "Center" %}</h2>
{% endblock content_title %}

{% block content %}
  <form action="" class="bg-white p-5 contact-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ formset.as_p }}
    {{ form|crispy }}
    <div class="form-group">
      <input type="submit" value='{% trans "Submit" %}' class="btn btn-primary py-3 px-5 mt-3">
    </div>
  </form>
{% endblock content %}

{% block project_js %}
  {{ block.super }}
  <script src={% static "vendor/jquery.formset.js" %}></script>
  <script src={% static "js/center_edit.js" %}></script>
{% endblock project_js %}

opencourse/templates/courses/course_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load auth_extras %}

{% block main %}
  <!-- Modal -->
  <div class="modal fade" id="contacts" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
       aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">{% trans "Contact" %} {{ professor }}:</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% trans "Telephone" %}: {{ professor.tel }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">{% trans "Ok" %}</button>
        </div>
      </div>
    </div>
  </div>

  <section class="ftco-section ftco-candidates ftco-candidates-2 bg-light pt-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 pr-lg-4">
          <div class="row">
            {% if professor %}
              <div class="col-md-12">
                <h3 class="h3 mb-5">{% trans "Professor" %}</h3>
              </div>
              <div class="col-md-12">
                <div class="team p-4 bg-white">
                  <div class="d-md-flex">
                    <div class="img" style="background-image: url(
                        {% if course.professor.picture %}
                          {{ course.professor.picture.url }}
                        {% else %}
                          {% static "images/no-avatar.png" %}
                        {% endif %}
                        );"></div>
                    <div class="text px-md-4" id="ReviewCountCl" onload="Rewiew()"
                         value='({{ reviews_count }} review{{ reviews_count|pluralize }})'>
                      <input class="rating-container score-display" value={{ professor.average_score|floatformat:"0" }}>
                      <h2>{{ professor }}</h2>
                      <p>
                        {% trans "City" %}: {{ professor.city|default:"" }}<br>
                        <!--{% trans "Date of birth" %}: {{ professor.dob|default:"" }} <br>-->
                        {{ professor.yearsexperience|default:"0" }} {% trans "years of experience" %}
                      </p>
                      {% if user.is_authenticated %}
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#contacts"
                                data-ajax-target='{% url "profiles:contact_request" professor.pk %}'
                                id="contact_request">
                          {% trans "Contact" %}
                        </button>
                      {% endif %}
                    </div>
                  </div>
                  <div class="pl-md-4">
                    <h2>{% trans "About me" %}</h2>
                    <p class="mb-2">{{ professor.bio|default:""|linebreaksbr }}</p>
                    <h2>{% trans "Education" %}</h2>
                    <p class="mb-2">{{ professor.edulevel|default:""|linebreaksbr }}</p>

                  </div>
                </div>
              </div>
            {% else %}
              <div class="col-md-12">
                <div class="team d-md-flex p-4 bg-white">
                  <div class="text pl-md-4">
                    <h2>{% trans "No professor found." %}</h2>
                  </div>
                </div>
              </div>
            {% endif %}
            {% if user.is_authenticated %}
              {% if page_obj %}
                <div class="col-md-12">
                  <h3 class="h3 mb-5 mt-3">{% trans "Courses" %}</h3>
                </div>
              {% endif %}
              {% include "components/course_body.html" %}
            {% endif %}
          </div>
          {% if is_paginated and user.is_authenticated %}
            <div class="row mt-5">
              <div class="col text-center">
                <div class="block-27">
                  {% include "components/pagination.html" %}
                </div>
              </div>
            </div>
          {% endif %}
        </div>
        <div class="col-lg-4 sidebar">
          <h3 class="h3 mb-5">{% trans "Reviews" %}</h3>
          {% if user.student %}
            <div class="sidebar-box bg-white p-4 ftco-animate fadeInUp ftco-animated">
              <h3 class="heading-sidebar">{% trans "Add review" %}</h3>
              <form action="{% url 'profiles:review_create' course.pk %}" class="contact-form signup"
                    method="post">
                {% csrf_token %}
                {{ review_form|crispy }}
                <div class="form-group">
                  <input type="submit" value='{% trans "Review" %}' class="btn btn-primary">
                </div>
              </form>
            </div>
          {% endif %}
          {% for review in reviews %}
            <div class="sidebar-box bg-white p-4 ftco-animate fadeInUp ftco-animated">
              <h3 class="heading-sidebar mb-0">{{ review.author }}</h3>
              <input class="score-display" value={{ review.score }}>
              <p>{{ review.text }}</p>
            </div>
          {% empty %}
            <div class="sidebar-box bg-white p-4 ftco-animate fadeInUp ftco-animated">
              <h3 class="heading-sidebar mb-0">{% trans "No reviews yet" %}</h3>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
{% endblock main %}

{% block project_js %}
  {{ block.super }}
  <script src={% static "js/course_detail.js" %}></script>
{% endblock project_js %}

opencourse/templates/courses/course_edit.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content_title %}
  <h2 class="h3">{% trans "Сourse" %}</h2>
{% endblock content_title %}

{% block content %}
  <form action="" class="bg-white p-5 contact-form" method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <h4 class="h4">{% trans "Locations" %}</h4>
    {% for location_form in formset %}
      <div class="row formset-row">
      {% for field in location_form.visible_fields %}
        <div class="col">{{ field|as_crispy_field }}</div>
      {% endfor %}
      </div>
      {% for field in location_form.hidden_fields %}
        {{ field|as_crispy_field }}
      {% endfor %}
    {% endfor %}
    <div class="form-group">
      <input type="submit" value='{% trans "Submit" %}' class="btn btn-primary py-3 px-5 mt-3">
    </div>
  </form>
{% endblock content %}

{% block project_js %}
  {{ block.super }}
  <script src={% static "vendor/jquery.formset.js" %}></script>
  <script src={% static "js/course_edit.js" %}></script>
{% endblock project_js %}

opencourse/templates/courses/course_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content_title %}
  <h2 class="h3">{% trans "Courses" %}</h2>
  <a class="btn btn-primary btn" href="{% url 'courses:create' %}">{% trans "Create course" %}</a>

{% endblock content_title %}

{% block content %}
  <ul class="list-group">
    {% for course in object_list %}
      <li class="list-group-item">
        <div class="row">
          <div class="col-sm-7 float-left">
            <a class="float-left" href="{% url 'courses:detail' course.pk %}">{{ course }}</a></div>
          <div class="col-sm-5 float-right">
            <a class="btn btn-outline-danger float-right mx-1 my-1 btn-sm " href="{% url 'courses:delete' course.pk %}"
               role="button"><span class="oi oi-trash"></span></a>
            <a class="btn btn-outline-warning float-right btn-sm  mx-1 my-1" href="{% url 'courses:edit' course.pk %}"
               role="button"><span class="oi oi-pencil "></span></a>
            <a class="btn btn-outline-info float-right btn-sm  mx-1 my-1"
               href="{% url 'courses:handouts:list' course.pk %}" role="button">
               <span class="oi oi-list"></span></a>
            <a class="btn btn-outline-info float-right btn-sm mx-1 my-1"
               href="{% url 'courses:students_list' course.pk %}" role="button">
               <span class="oi oi-people"></span></a>
          </div>
        </div>
      </li>
    {% empty %}
      <li class="list-group-item">{% trans "No courses yet." %}</li>
    {% endfor %}
  </ul>
{% endblock content %}

opencourse/templates/courses/course_search.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
  {{ block.super }}
  <link rel="stylesheet" href={% static "css/search.css" %} type="text/css"/>
{% endblock css %}

{% block header_content %}
  <div class="container">
    <div class="row d-md-flex no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-7 d-flex align-items-center ftco-animate">
        <div class="text text-center pt-5 mt-md-5">
          
          <h1 class="mb-5">{% trans "What do you want to learn?" %}</h1>
          <div class="ftco-counter ftco-no-pt ftco-no-pb">
            <div class="row">
              <div class="col-md-4 d-flex justify-content-center counter-wrap ftco-animate">
                <div class="block-18">
                  <div class="text d-flex">
                    <div class="icon mr-2">
                      <span class="flaticon-worldwide"></span>
                    </div>
                    <div class="desc text-left">
                      <strong class="number" data-number="46">46</strong>
                      <span>{% trans "Cities" %}</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4 d-flex justify-content-center counter-wrap ftco-animate">
                <div class="block-18 text-center">
                  <div class="text d-flex">
                    <div class="icon mr-2">
                      <span class="flaticon-visitor"></span>
                    </div>
                    <div class="desc text-left">
                      <strong class="number" data-number="450">0</strong>
                      <span>{% trans "Professors" %}</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4 d-flex justify-content-center counter-wrap ftco-animate">
                <div class="block-18 text-center">
                  <div class="text d-flex">
                    <div class="icon mr-2">
                      <span class="flaticon-resume"></span>
                    </div>
                    <div class="desc text-left">
                      <strong class="number" data-number="80000">0</strong>
                      <span>{% trans "Students" %}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="ftco-search my-md-5">
            <div class="row">
              <div class="col-md-12 nav-link-wrap">
                <div class="nav nav-pills text-center" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                  <a class="nav-link active mr-md-1" id="v-pills-1-tab" data-toggle="pill" href="#v-pills-1"
                     role="tab" aria-controls="v-pills-1" aria-selected="true">{% trans "Find a Professor" %}</a>
                  <a class="nav-link" id="v-pills-2-tab" data-toggle="pill" href="#v-pills-2"
                    role="tab" aria-controls="v-pills-2" aria-selected="false">{% trans "Find a Center" %}</a>
                </div>
              </div>
              <div class="col-md-12 tab-wrap">
                <div class="tab-content p-4" id="v-pills-tabContent">
                  <div class="tab-pane fade show active" id="v-pills-1" role="tabpanel" aria-labelledby="v-pills-nextgen-tab">
                    <form action="{% url 'courses:search_results' %}" class="search-job">
                      <div class="row no-gutters">
                        <div class="col-md mr-md-2">
                                {{ form.city|as_crispy_field }}
                        </div>
                        <div class="col-md mr-md-2">
                                {{ form.area|as_crispy_field }}
                        </div>
                        <div class="col-md-3">
                          <div class="form-group">
                            <div class="form-field">
                              <button type="submit" class="form-control btn btn-primary">{% trans "Search" %}</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                  <div class="tab-pane fade" id="v-pills-2" role="tabpanel"
                    aria-labelledby="v-pills-performance-tab">
                    <form action="{% url 'courses:centers:search_results' %}" id="center_search" class="search-job" method="get">
                      <div class="row no-gutters">
                        <div class="col-md mr-md-2">
                          {{ form.name|as_crispy_field }}
                        </div>
                        <div class="col-md-3">
                          <div class="form-group">
                            <div class="form-field">
                              <button type="submit" class="form-control btn btn-primary">{% trans "Search" %}</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              <p class="mb-4">{% trans "From math tutoring to yoga, Superprof is the best and fastest way to find high-quality teachers." %}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock header_content %}

{% block main %}
{% endblock main %}

{% block footer %}
{% endblock footer %}