config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from opencourse.profiles.views import ProfileView

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/profile/", ProfileView.as_view()),
    path("profiles/", include("opencourse.profiles.urls", namespace="profiles")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("courses/", include("opencourse.courses.urls", namespace="courses")),
    path("", RedirectView.as_view(pattern_name="courses:search")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path("rosetta/", include("rosetta.urls"))]

opencourse/courses/urls.py
from django.urls import path, include
from django.views.generic import RedirectView

from . import views

app_name = "courses"

course_patterns = [
    path("list/", views.CourseListView.as_view(), name="list"),
    path("create/", views.CourseCreateView.as_view(), name="create"),
    path("detail/<int:pk>/", views.CourseDetailView.as_view(), name="detail"),
    path("edit/<int:pk>/", views.CourseEditView.as_view(), name="edit"),
    path("delete/<int:pk>/", views.CourseDeleteView.as_view(), name="delete"),
    path("search/", views.CourseSearchView.as_view(), name="search"),
    path(
        "<int:pk>/students/",
        views.CourseStudentsListView.as_view(),
        name="students_list",
    ),
    path(
        "search-results/",
        views.CourseSearchResultsView.as_view(),
        name="search_results",
    ),
]

enrollment_patterns = [
    path(
        "professor/", views.EnrollmentProfessorListView.as_view(), name="professor_list"
    ),
    path("student/", views.EnrollmentStudentListView.as_view(), name="student_list"),
    path("create", views.EnrollmentCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.EnrollmentUpdateStatusView.as_view(), name="edit"),
]

handout_patterns = [
    path("list/<int:course_pk>/", views.HandoutListView.as_view(), name="list"),
    path("create/<int:course_pk>/", views.HandoutCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.HandoutUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", views.HandoutDeleteView.as_view(), name="delete"),
]

center_patterns = [
    path("list/", views.CenterListView.as_view(), name="list"),
    path("create/", views.CenterCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.CenterEditView.as_view(), name="edit"),
    path("delete/<int:pk>/", views.CenterDeleteView.as_view(), name="delete"),
    path("detail/<int:pk>/", views.CenterDetailView.as_view(), name="detail"),
    path(
        "search-results/",
        views.CenterSearchResultsView.as_view(),
        name="search_results",
    ),
]

join_request_patterns = [
    path("admin/", views.JoinRequestrListView.as_view(), name="admin_list"),
    path("create/", views.JoinRequestCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.JoinRequestUpdateView.as_view(), name="edit"),
]

urlpatterns = [
    path("", include(course_patterns)),
    path(
        "enrollments/",
        include((enrollment_patterns, "opencourse.courses"), namespace="enrollments"),
    ),
    path(
        "handouts/",
        include((handout_patterns, "opencourse.courses"), namespace="handouts"),
    ),
    path(
        "centers/",
        include((center_patterns, "opencourse.courses"), namespace="centers"),
    ),
    path(
        "join_requests/",
        include(
            (join_request_patterns, "opencourse.courses"), namespace="join_requests"
        ),
    ),
]

opencourse/profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"
urlpatterns = [
    path("", views.ProfileView.as_view(), name="profile"),
    path("dispatch-login/", views.DispatchLoginView.as_view(), name="dispatch_login",),
    path("professor/", views.ProfessorUpdateView.as_view(), name="professor"),
    path(
        "professor/<int:pk>/add-review",
        views.ReviewCreateView.as_view(),
        name="review_create",
    ),
    path(
        "professor/<int:pk>/contact-request/",
        views.ContactRequestView.as_view(),
        name="contact_request",
    ),
    path("student/", views.StudentUpdateView.as_view(), name="student"),
    path("403/", views.ForbiddenView.as_view(), name="403"),
]

opencourse/courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    ListView,
    FormView,
    UpdateView,
    DetailView,
    DeleteView,
    View,
)

from django_filters.views import FilterView
from guardian.mixins import PermissionRequiredMixin
from guardian.shortcuts import assign_perm

from . import forms, models, filters
from opencourse.profiles.models import Student
from .mixins import FormsetMixin, JsonFormMixin
from opencourse.profiles.forms import ReviewForm
from opencourse.profiles.mixins import ProfessorRequiredMixin, StudentRequiredMixin
from django.views.generic.list import MultipleObjectMixin


REVIEW_COUNT = 10


class CoursePermissionRequiredMixin(PermissionRequiredMixin):
    permission_required = "courses.manage_course"
    return_403 = True


class CourseEditView(CoursePermissionRequiredMixin, FormsetMixin, UpdateView):
    model = models.Course
    form_class = forms.CourseForm
    formset_class = forms.CourseLocationFormset
    template_name = "courses/course_edit.html"
    exclude = ["professor"]
    success_url = reverse_lazy("courses:list")
    permission_required = "courses.manage_course"
    return_403 = True

    def get_form_kwargs(self):
        kwargs = super(CourseEditView, self).get_form_kwargs()
        kwargs.update({"professor": self.request.user.professor})
        return kwargs


class CourseCreateView(ProfessorRequiredMixin, FormsetMixin, CreateView):
    model = models.Course
    form_class = forms.CourseForm
    formset_class = forms.CourseLocationFormset
    template_name = "courses/course_edit.html"
    exclude = ["professor"]
    success_url = reverse_lazy("courses:list")

    def form_valid(self, form):
        with transaction.atomic():
            form.instance.professor = self.request.user.professor
            response = super().form_valid(form)
            course = self.object
            assign_perm("manage_course", course.professor.user, course)
            return response

    def get_initial(self):
        initial = {
            "area": 1,
            "level": 1,
            "language": 1,
            "duration": 1,
            "age": 1,
            "city": 1,
            "center": 1,
        }
        return initial

    def get_form_kwargs(self):
        kwargs = super(CourseCreateView, self).get_form_kwargs()
        kwargs.update({"professor": self.request.user.professor})
        return kwargs


class CourseListView(ProfessorRequiredMixin, ListView):
    template_name = "courses/course_list.html"
    paginate_by = 100  # if pagination is desired

    def get_queryset(self):
        professor = self.request.user.professor
        return models.Course.objects.created_by(professor=professor)


class CourseDetailView(DetailView):
    model = models.Course
    template_name = "courses/course_detail.html"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        kwargs["review_form"] = ReviewForm()
        kwargs["professor"] = self.object.professor
        kwargs["reviews"] = self.object.professor.review_set.order_by("-id")[
            :REVIEW_COUNT
        ]
        kwargs["reviews_count"] = kwargs["reviews"].count()
        student = getattr(self.request.user, "student", None)
        kwargs["enrollment_form"] = forms.EnrollmentCreateForm(
            initial={"course": self.object, "student": student},
        )
        enrollment = models.Enrollment.objects.filter(
            course=self.object, student=student
        ).first()
        kwargs["enrollment_accepted"] = getattr(enrollment, "accepted", "not_existing")

        return super().get_context_data(**kwargs)


class CourseDeleteView(CoursePermissionRequiredMixin, DeleteView):
    model = models.Course
    success_url = reverse_lazy("courses:list")
    template_name = "confirm_delete.html"


class CourseSearchView(FormView):
    template_name = "courses/course_search.html"
    form_class = forms.CourseSearchForm
    success_url = reverse_lazy("courses:search")


class CourseSearchResultsView(FilterView):
    filterset_class = filters.CourseFilter
    template_name = "courses/course_search_results.html"
    paginate_by = 10


class HandoutListView(LoginRequiredMixin, ListView):
    model = models.Handout
    template_name = "courses/handout_list.html"

    def get_queryset(self):
        course_pk = self.kwargs.get("course_pk")
        course = get_object_or_404(models.Course, pk=course_pk)
        object_list = self.model.objects.filter(course=course).order_by("section")
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course_pk = self.kwargs.get("course_pk")
        context["course"] = get_object_or_404(models.Course, pk=course_pk)
        return context

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_student:
            course_pk = self.kwargs.get("course_pk")
            course = get_object_or_404(models.Course, pk=course_pk)
            student = self.request.user.student
            enrollment = models.Enrollment.objects.filter(
                course=course, student=student
            ).first()
            has_access = getattr(enrollment, "accepted", False)
            if not has_access:
                return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class HandoutUpdateView(ProfessorRequiredMixin, UpdateView):
    model = models.Handout
    form_class = forms.HandoutForm
    template_name = "courses/handout_edit.html"

    def get_success_url(self):
        handout_pk = self.kwargs.get("pk")
        course = get_object_or_404(models.Course, handout=handout_pk)
        return reverse("courses:handouts:list", kwargs={"course_pk": course.pk})


class HandoutDeleteView(ProfessorRequiredMixin, DeleteView):
    model = models.Handout
    template_name = "confirm_delete.html"

    def get_success_url(self):
        handout_pk = self.kwargs.get("pk")
        course = get_object_or_404(models.Course, handout=handout_pk)
        return reverse("courses:handouts:list", kwargs={"course_pk": course.pk})


class HandoutCreateView(ProfessorRequiredMixin, CreateView):
    model = models.Handout
    form_class = forms.HandoutForm
    template_name = "courses/handout_edit.html"

    def form_valid(self, form):
        course_pk = self.kwargs.get("course_pk")
        form.instance.course = get_object_or_404(models.Course, pk=course_pk)
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        course_pk = self.kwargs.get("course_pk")
        return reverse("courses:handouts:list", kwargs={"course_pk": course_pk})


class EnrollmentUpdateStatusView(ProfessorRequiredMixin, JsonFormMixin, UpdateView):
    model = models.Enrollment
    fields = ["accepted"]


class EnrollmentCreateView(LoginRequiredMixin, JsonFormMixin, CreateView):
    model = models.Enrollment
    form_class = forms.EnrollmentCreateForm


class EnrollmentStudentListView(StudentRequiredMixin, ListView):
    model = models.Enrollment
    template_name = "courses/enrollment_list.html"

    def get_queryset(self):
        object_list = self.model.objects.filter(
            student=self.request.user.student, accepted=True
        )
        return object_list


class EnrollmentProfessorListView(ProfessorRequiredMixin, ListView):
    model = models.Enrollment
    template_name = "courses/enrollment_list.html"

    def get_queryset(self):
        object_list = self.model.objects.filter(
            course__professor=self.request.user.professor
        ).order_by("accepted")
        return object_list


class CourseStudentsListView(ProfessorRequiredMixin, ListView):
    model = models.Course
    template_name = "courses/course_students_list.html"
    paginate_by = 100  # if pagination is desired

    def get_queryset(self):
        course = get_object_or_404(models.Course, pk=self.kwargs.get("pk"))
        students = Student.objects.filter(
            enrollment__course=course, enrollment__accepted=True
        )
        return students


class CenterCreateView(ProfessorRequiredMixin, CreateView):
    model = models.Center
    template_name = "courses/center_edit.html"
    form_class = forms.CenterForm
    success_url = reverse_lazy("courses:centers:list")

    def form_valid(self, form):
        form.instance.admin = self.request.user.professor
        form.save()
        return super().form_valid(form)


class CenterEditView(ProfessorRequiredMixin, UpdateView):
    model = models.Center
    template_name = "courses/center_edit.html"
    form_class = forms.CenterForm
    success_url = reverse_lazy("courses:centers:list")

    def form_valid(self, form):
        form.instance.admin = self.request.user.professor
        form.save()
        return super().form_valid(form)


class CenterListView(ProfessorRequiredMixin, ListView):
    template_name = "courses/centers_list.html"

    def get_queryset(self, *args, **kwargs):
        professor = self.request.user.professor
        return models.Center.objects.created_by(admin=professor)

    def get_context_data(self, **kwargs):
        professor = getattr(self.request.user, "professor", None)
        kwargs["join_centers"] = models.JoinRequest.objects.filter(
            professor=professor, accepted=True
        )

        return super().get_context_data(**kwargs)


class CenterDetailView(DetailView, MultipleObjectMixin):
    model = models.Center
    template_name = "courses/center_detail.html"
    paginate_by = 3

    def get_context_data(self, **kwargs):
        professor = getattr(self.request.user, "professor", None)
        kwargs["join_request_form"] = forms.JoinRequestCreateForm(
            initial={"center": self.object, "professor": professor},

opencourse/templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% trans "SuperProf" %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {% block css %}
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/open-iconic-bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/animate.css" %}>
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/owl.carousel.min.css" %}>
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/owl.theme.default.min.css" %}>
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/magnific-popup.css" %}>
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/aos.css" %}>
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/ionicons.min.css" %}>
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/bootstrap-datepicker.css" %}>
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/jquery.timepicker.css" %}>
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/flaticon.css" %}>
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/icomoon.css" %}>
    <link rel="stylesheet" href={% static "vendor/skillhunt/css/style.css" %}>


    <link href={% static "vendor/bootstrap-select/bootstrap-select.min.css" %} rel="stylesheet">
    <link href={% static "vendor/bootstrap-star-rating/css/star-rating.css" %} media="all" rel="stylesheet">
    <link href={% static "vendor/bootstrap-star-rating/themes/krajee-uni/theme.css" %} media="all" rel="stylesheet">
    <link href={% static "css/main.css" %} rel="stylesheet">
  {% endblock css %}
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container-fluid px-md-4	">
    <a class="navbar-brand" href="{% url 'courses:search' %}">
      <img src="{% static 'images/logosm.png' %}" alt="Super-Prof">
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> {% trans "Menu" %}
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a href="{% url 'courses:search' %}" class="nav-link">{% trans "Home" %}</a></li>
        {% if user.is_student %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'courses:enrollments:student_list' %}">{% trans "Enrollments" %}</a>
          </li>
        {% elif user.professor %}
          <li class="nav-item"><a class="nav-link" href="{% url 'courses:list' %}">{% trans "Courses" %}</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'courses:centers:list' %}">{% trans "Centers" %}</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'courses:enrollments:professor_list' %}">{% trans "Enrollments" %}</a></li>
        {% endif %}
        {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'courses:search_results' %}">{% trans "Search results" %}</a>
          </li>
        {% endif %}
        <li class="nav-item dropdown show">
          {% get_current_language as LANGUAGE_CODE %}
          {% get_language_info for LANGUAGE_CODE as lang %}
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          <form action="{% url 'set_language' %}" method="post" id="change-language-form">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <input type="hidden" value="" name="language" id="language"/>
          </form>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
             aria-haspopup="true" aria-expanded="false">
            {{ lang.name_local }}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for language in languages %}
          		{% with "images/"|add:language.code|add:".png" as imagestatic %}
                <a class="dropdown-item change-language" href="#"
                 data-lang-code="{{ language.code }}">{{ language.name_local }}
                ({{ language.code }}) <img src="{% static imagestatic %}" width="20" height="16" style="float: right;">  </a>
                {% endwith %}
              <!--<a class="dropdown-item change-language" href="#"
                 data-lang-code="{{ language.code }}">{{ language.name_local }}
                ({{ language.code }})</a> -->
            {% endfor %}
          </div>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item cta mr-md-1">
            <a href="{% url 'profiles:profile' %}" class="nav-link">{% trans "Profile" %}</a>
          </li>
          <li class="nav-item cta cta-colored">
            <a href="{% url 'account_logout' %}" class="nav-link">{% trans "Logout" %}</a>
          </li>
        {% elif not user.is_authenticated %}
          <li class="nav-item cta mr-md-1">
            <a href="{% url 'account_login' %}" class="nav-link">{% trans "Login" %}</a>
          </li>
          <li class="nav-item cta cta-colored">
            <a href="{% url 'account_signup' %}" class="nav-link">{% trans "Signup" %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- END nav -->

<div class="hero-wrap img"
     style="background-image: url({% static "vendor/skillhunt/images/bg_1.jpg" %});">
  <div class="overlay"></div>
  {% block header_content %}{% endblock header_content %}
</div>

<!--Content-->
{% block main %}
  <section class="ftco-section contact-section bg-light pt-5">
    <div class="container">
      <div class="row d-flex contact-info">
        <div class="col-md-12 mb-4">
          {% block content_title %}
            <h2 class="h3"></h2>
          {% endblock content_title %}
        </div>
      </div>
      <div class="row block-9">
        <div class="col-md-6 order-md-last d-flex flex-column">
          {% block content %}{% endblock content %}
        </div>
      </div>
    </div>
  </section>
{% endblock main %}

{% block footer %}
  <footer class="footer">
    <div class="container">
          <span class="text-muted">
              {% trans "Copyright" %} © <script>document.write(new Date().getFullYear());</script>
              {% trans "All rights reserved" %}
              
          </span>
    </div>
  </footer>
{% endblock footer %}

<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
  <svg class="circular" width="48px" height="48px">
    <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
    <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/>
  </svg>
</div>

<script src="{% url 'javascript-catalog' %}"></script>
<script src={% static "vendor/skillhunt/js/jquery.min.js" %}></script>
<script src={% static "vendor/skillhunt/js/jquery-migrate-3.0.1.min.js" %}></script>
<script src={% static "vendor/skillhunt/js/popper.min.js" %}></script>
<script src={% static "vendor/skillhunt/js/bootstrap.min.js" %}></script>
<script src={% static "vendor/skillhunt/js/jquery.easing.1.3.js" %}></script>
<script src={% static "vendor/skillhunt/js/jquery.waypoints.min.js" %}></script>
<script src={% static "vendor/skillhunt/js/jquery.stellar.min.js" %}></script>
<script src={% static "vendor/skillhunt/js/owl.carousel.min.js" %}></script>
<script src={% static "vendor/skillhunt/js/jquery.magnific-popup.min.js" %}></script>
<script src={% static "vendor/skillhunt/js/aos.js" %}></script>
<script src={% static "vendor/skillhunt/js/jquery.animateNumber.min.js" %}></script>
<script src={% static "vendor/skillhunt/js/scrollax.min.js" %}></script>
<script src={% static "vendor/skillhunt/js/main.js" %}></script>

<script src={% static "vendor/bootstrap-select/bootstrap-select.min.js" %}></script>
<script src={% static "vendor/bootstrap-star-rating/js/star-rating.js" %} type="text/javascript"></script>
<script src={% static "vendor/bootstrap-star-rating/themes/krajee-uni/theme.js" %} type="text/javascript"></script>
{% block project_js %}
  <script src={% static "js/main.js" %}></script>
{% endblock project_js %}
</body>
</html>

opencourse/templates/confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content_title %}
  <h2 class="h3">{% trans "Confirmation" %}</h2>
{% endblock content_title %}

{% block content %}
  <ul class="list-group">
    <li class="list-group-item p-4">
      <form method="post">{% csrf_token %}
        <p>{% trans "Are you sure you want to delete" %} "{{ object }}"?</p>
        <input type="submit" class="btn btn-primary" value="Confirm">
      </form>
    </li>
  </ul>
{% endblock content %}